import { describe, expect, it } from 'vitest'
import { applyTrade, basePrice, cardFromValue, chooseHiddenIndexes, createPlayers, difficultyCardCount, eventsFor, generateCards, maxQuantity, quoteOutsideValue, randomOrder, resolveBotTrades, STARTING_BUDGET, resolveUserTrade, truePrice, validateQuote, validateTrade } from './hiddenSpread'

describe('Hidden Spread domain', () => {
  it('maps face cards and difficulty sizes', () => { expect(cardFromValue(11).label).toBe('J'); expect(cardFromValue(12).label).toBe('Q'); expect(cardFromValue(13).label).toBe('K'); expect(cardFromValue(14).label).toBe('A'); expect(generateCards('Easy')).toHaveLength(3); expect(generateCards('Medium')).toHaveLength(5); expect(generateCards('Hard')).toHaveLength(7); expect(difficultyCardCount('Hard')).toBe(7); expect(generateCards('Easy').every(card => card.value >= 2 && card.value <= 14)).toBe(true) })
  it('keeps one to three hidden cards', () => { for (const count of [3, 5, 7]) { const hidden = chooseHiddenIndexes(count, () => .2); expect(hidden.length).toBeGreaterThanOrEqual(1); expect(hidden.length).toBeLessThanOrEqual(3); expect(new Set(hidden).size).toBe(hidden.length) } })
  it('calculates base and event price', () => { const cards = [{ value: 11, label: 'J' }, { value: 12, label: 'Q' }]; expect(basePrice(cards)).toBe(23); expect(truePrice(cards, eventsFor('Medium')[0])).toBeCloseTo(26.45) })
  it('validates quotes and budget-limited trades', () => { expect(validateQuote({ bid: 10, ask: 11 })).toBe(true); expect(validateQuote({ bid: 10.5, ask: 11 })).toBe(false); expect(validateQuote({ bid: 10, ask: 17 })).toBe(false); expect(validateQuote({ bid: 11, ask: 10 })).toBe(false); expect(validateTrade(100, 'buy', 11, 9)).toBe(true); expect(validateTrade(100, 'buy', 11, 10)).toBe(false); expect(maxQuantity(100, 11)).toBe(9) })
  it('keeps bot quotes outside the true value', () => { const quote = quoteOutsideValue({ bid: 10, ask: 14 }, 12); expect(quote.ask < 12 || quote.bid > 12).toBe(true); expect(quote.ask - quote.bid).toBeLessThanOrEqual(6) })
  it('updates budgets on both sides', () => { const player = createPlayers()[0]; expect(applyTrade(player, 'buy', 10, 3).budget).toBe(9970); expect(applyTrade(player, 'sell', 10, 3).budget).toBe(10030); expect(resolveUserTrade(player, { bid: 9, ask: 11 }, 'buy', 2).trade?.value).toBe(22) })
  it('settles bot trades against the user maker', () => { const players = createPlayers(); const result = resolveBotTrades(players, { bid: 9, ask: 10 }, 20, () => .1); expect(result.trades.length).toBeGreaterThan(0); expect(result.players.find(player => player.id === 'user')!.budget).toBeGreaterThan(STARTING_BUDGET) })
  it('creates five players and one user maker in a permutation', () => { const order = randomOrder(() => .1); expect(order).toHaveLength(5); expect(new Set(order).size).toBe(5); expect(order.filter(id => id === 'user')).toHaveLength(1); expect(createPlayers()).toHaveLength(5) })
})
