export type VenueGapDifficulty = 'Easy' | 'Medium' | 'Hard'
export type VenueGapAction = 'arbitrage' | 'skip' | 'timeout'
export type VenueQuote = { venueId: string; name: string; bid: number; ask: number; bidQuantity: number; askQuantity: number; feeRate: number }
export type VenueGapRound = { asset: string; venues: VenueQuote[]; hasOpportunity: boolean }
export type VenueGapTrade = { buyVenueId: string; sellVenueId: string; quantity: number; buyPrice: number; sellPrice: number; buyFee: number; sellFee: number; netProfit: number }
export type VenueGapPlayer = { budget: number }
export const VENUE_GAP_ROUNDS = 5
export const VENUE_GAP_SECONDS = 60
export const VENUE_GAP_STARTING_BUDGET = 10_000
const randomInt = (max: number, random: () => number) => Math.floor(Math.max(0, Math.min(.999999, random())) * max)
export const venueCountFor = (difficulty: VenueGapDifficulty) => ({ Easy: 2, Medium: 3, Hard: 4 }[difficulty])
export const feeRatesFor = (difficulty: VenueGapDifficulty) => difficulty === 'Easy' ? [0, 0] : difficulty === 'Medium' ? [.001, .0015, .002] : [.0015, .002, .0025, .0035]
export function validateVenueQuote(venue: VenueQuote) { return Number.isInteger(venue.bid) && Number.isInteger(venue.ask) && venue.bid > 0 && venue.ask > venue.bid && Number.isInteger(venue.bidQuantity) && Number.isInteger(venue.askQuantity) && venue.bidQuantity > 0 && venue.askQuantity > 0 && venue.feeRate >= 0 }
export function grossProfit(buy: VenueQuote, sell: VenueQuote, quantity: number) { return (sell.bid - buy.ask) * quantity }
export function calculateTrade(buy: VenueQuote, sell: VenueQuote, quantity: number): VenueGapTrade | null { if (buy.venueId === sell.venueId || !validateVenueQuote(buy) || !validateVenueQuote(sell) || !Number.isInteger(quantity) || quantity < 1 || quantity > buy.askQuantity || quantity > sell.bidQuantity) return null; const buyCost = buy.ask * quantity; const sellRevenue = sell.bid * quantity; const buyFee = buyCost * buy.feeRate; const sellFee = sellRevenue * sell.feeRate; return { buyVenueId: buy.venueId, sellVenueId: sell.venueId, quantity, buyPrice: buy.ask, sellPrice: sell.bid, buyFee, sellFee, netProfit: sellRevenue - buyCost - buyFee - sellFee } }
export function maxTradeQuantity(budget: number, buy: VenueQuote, sell: VenueQuote) { if (!validateVenueQuote(buy) || !validateVenueQuote(sell) || buy.venueId === sell.venueId || budget < 0) return 0; return Math.min(buy.askQuantity, sell.bidQuantity, Math.floor(budget / (buy.ask * (1 + buy.feeRate)))) }
export function resolveTrade(player: VenueGapPlayer, buy: VenueQuote, sell: VenueQuote, quantity: number) { const trade = calculateTrade(buy, sell, quantity); if (!trade || quantity > maxTradeQuantity(player.budget, buy, sell)) return { player, trade: null }; return { player: { budget: Number((player.budget + trade.netProfit).toFixed(2)) }, trade } }
export function resolveAction(action: VenueGapAction, player: VenueGapPlayer, buy: VenueQuote | null, sell: VenueQuote | null, quantity: number) { if (action !== 'arbitrage' || !buy || !sell) return { player, trade: null }; return resolveTrade(player, buy, sell, quantity) }
export function findBestOpportunity(venues: readonly VenueQuote[]) { let best: VenueGapTrade | null = null; for (const buy of venues) for (const sell of venues) { if (buy.venueId === sell.venueId) continue; const quantity = Math.min(buy.askQuantity, sell.bidQuantity); const trade = calculateTrade(buy, sell, quantity); if (trade && (!best || trade.netProfit > best.netProfit)) best = trade } return best && best.netProfit > 0 ? best : null }
export function createRound(difficulty: VenueGapDifficulty, roundIndex = 0, random = Math.random): VenueGapRound { const count = venueCountFor(difficulty); const fees = feeRatesFor(difficulty); const base = 20 + randomInt(15, random); const opportunity = roundIndex % 3 !== 1; const venues = Array.from({ length: count }, (_, index) => { const ask = base + 2 + index * 2 + randomInt(3, random); const bid = ask - 1 - randomInt(3, random); return { venueId: `venue-${index + 1}`, name: `Venue ${String.fromCharCode(65 + index)}`, bid, ask, bidQuantity: difficulty === 'Hard' ? 1 + randomInt(8, random) : 8, askQuantity: difficulty === 'Hard' ? 1 + randomInt(8, random) : 8, feeRate: fees[index] } }); if (opportunity) { venues[0].ask = base - 1; venues[0].bid = base - 3; venues[0].askQuantity = difficulty === 'Hard' ? 2 : 8; venues[1].bid = base + 4; venues[1].ask = base + 6; venues[1].bidQuantity = difficulty === 'Hard' ? 2 : 8 } else { venues.forEach((venue, index) => { venue.ask = base + 3 + index; venue.bid = venue.ask - 1 }) } return { asset: 'QPX', venues, hasOpportunity: Boolean(findBestOpportunity(venues)) } }
